Homework2_Parallel : Part_2_Parallel.o timing.o
	gcc -o Homework2_Parallel Part_2_Parallel.o timing.o -lpthread

Part_2_Parallel.o : Part_2_Parallel.c
	gcc -c Part_2_Parallel.c

timing.o : timing.c
	gcc -c timing.c
