Part_3_Parallel : Part_3_Parallel.o timing.o
	gcc -o Part_3_Parallel Part_3_Parallel.o timing.o -lpthread

Part_3_Parallel.o : Part_3_Parallel.c
	gcc -c Part_3_Parallel.c

timing.o : timing.c
	gcc -c timing.c
