Part_1_Serial : GetNumbers.o timing.o ArrayStackImplement.o ArrayStackMain.o
	gcc -o Part_1_Serial GetNumbers.o timing.o ArrayStackImplement.o ArrayStackMain.o

GetNumbers.o : GetNumbers.c
	gcc -c GetNumbers.c

timing.o : timing.c
	gcc -c timing.c
ArrayStackImplement.o : ArrayStackImplement.c
	gcc -c ArrayStackImplement.c

ArrayStackMain.o : ArrayStackMain.c
	gcc -c ArrayStackMain.c